{
  "swagger": "2.0",
  "info": {
    "version": "2017-09-01-preview",
    "title": "MonitorManagementClient",
    "x-ms-code-generation-settings": {
      "name": "MonitorManagementClient"
    },
    "description": "Azure Monitor client to create/update/delete metric based alerts."
  },
  "host": "management.azure.com",
  "schemes": [ "https" ],
  "consumes": [ "application/json" ],
  "produces": [ "application/json" ],
  "security": [
    {
      "azure_auth": [
        "user_impersonation"
      ]
    }
  ],
  "securityDefinitions": {
    "azure_auth": {
      "type": "oauth2",
      "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize",
      "flow": "implicit",
      "description": "Azure Active Directory OAuth2 Flow",
      "scopes": {
        "user_impersonation": "impersonate your user account"
      }
    }
  },
  "paths": {
    "/subscriptions/{subscriptionId}/providers/Microsoft.Insight/metricAlerts": {
      "get": {
        "tags": [ "MetricAlerts" ],
        "description": "Retrieve alert rule definitions in a subscription.",
        "operationId": "MetricAlerts_ListBySubscription",
        "parameters": [
          { "$ref": "#/parameters/SubscriptionIdParameter" },
          { "$ref": "#/parameters/ApiVersionParameter" }
        ],
        "responses": {
          "200": {
            "description": "Successful request for a list of metric alerts",
            "schema": {
              "$ref": "#/definitions/MetricAlertResourceCollection"
            },
            "examples": {
              "application/json": {
                "value": [
                  {
                    "location": "global",
                    "tags": {
                      "key1": "value1",
                      "key2": "value2"
                    },
                    "id": "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourcegroups/test/providers/microsoft.insights/metricalerts/storageTest",
                    "name": "storageTest",
                    "properties": {
                      "description": "This is the description of the xstore multidim rule1",
                      "severity": 3,
                      "enabled": true,
                      "scopes": [
                        "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/test/providers/Microsoft.Storage/storageAccounts/testmultidim/blobServices/default"
                      ],
                      "evaluationFrequency": "PT1M",
                      "windowSize": "PT15M",
                      "criteriaSchemaId": "SingleResourceMultipleMetricCriteria",
                      "criteria": {
                        "allOf": [
                          {
                            "name": "HowManyBytes",
                            "metricName": "BlobCapacity",
                            "dimensions": [
                              {
                                "name": "BlobType",
                                "operator": "Include",
                                "values": [
                                  "BlockBlob",
                                  "PageBlob"
                                ]
                              }
                            ],
                            "operator": "GreaterThanOrEqual",
                            "threshold": 5.0,
                            "timeAggregation": "Maximum"
                          }
                        ]
                      },
                      "actions": [
                        {
                          "actionGroupId": "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/test/providers/microsoft.insights/actionGroups/testActionGroup"
                        }
                      ],
                      "currentStatus": {
                        "value": "Healthy",
                        "timestamp": "2018-01-17T20:17:25.6293237Z"
                      }
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "BadRequest",
            "schema": { "$ref": "#/definitions/CloudError" }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": null
        },
        "x-ms-examples": {
          "List metric alert rules": { "$ref": "./examples/listMetricAlert.json" }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insight/metricAlerts": {
      "get": {
        "tags": [ "MetricAlerts" ],
        "description": "Retrieve alert rule defintions in a resource group.",
        "operationId": "MetricAlerts_ListByResourceGroup",
        "parameters": [
          { "$ref": "#/parameters/SubscriptionIdParameter" },
          { "$ref": "#/parameters/ResourceGroupNameParameter" },
          { "$ref": "#/parameters/ApiVersionParameter" }
        ],
        "responses": {
          "200": {
            "description": "Successful request for a list of metric alerts",
            "schema": {
              "$ref": "#/definitions/MetricAlertResourceCollection"
            },
            "examples": {
              "application/json": {
                "value": [
                  {
                    "location": "global",
                    "tags": {
                      "key1": "value1",
                      "key2": "value2"
                    },
                    "id": "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourcegroups/test/providers/microsoft.insights/metricalerts/storageTest",
                    "name": "storageTest",
                    "properties": {
                      "description": "This is the description of the xstore multidim rule1",
                      "severity": 3,
                      "enabled": true,
                      "scopes": [
                        "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/test/providers/Microsoft.Storage/storageAccounts/testmultidim/blobServices/default"
                      ],
                      "evaluationFrequency": "PT1M",
                      "windowSize": "PT15M",
                      "criteriaSchemaId": "SingleResourceMultipleMetricCriteria",
                      "criteria": {
                        "allOf": [
                          {
                            "name": "HowManyBytes",
                            "metricName": "BlobCapacity",
                            "dimensions": [
                              {
                                "name": "BlobType",
                                "operator": "Include",
                                "values": [
                                  "BlockBlob",
                                  "PageBlob"
                                ]
                              }
                            ],
                            "operator": "GreaterThanOrEqual",
                            "threshold": 5.0,
                            "timeAggregation": "Maximum"
                          }
                        ]
                      },
                      "actions": [
                        {
                          "actionGroupId": "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/test/providers/microsoft.insights/actionGroups/testActionGroup"
                        }
                      ],
                      "currentStatus": {
                        "value": "Healthy",
                        "timestamp": "2018-01-17T20:17:25.6293237Z"
                      }
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "BadRequest",
            "schema": { "$ref": "#/definitions/CloudError" }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": null
        },
        "x-ms-examples": {
          "List metric alert rules": { "$ref": "./examples/listMetricAlert.json" }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insight/metricAlerts/{ruleName}": {
      "get": {
        "tags": [ "MetricAlerts" ],
        "description": "Retrieve an alert rule definiton.",
        "operationId": "MetricAlerts_Get",
        "parameters": [
          { "$ref": "#/parameters/SubscriptionIdParameter" },
          { "$ref": "#/parameters/ResourceGroupNameParameter" },
          { "$ref": "#/parameters/RuleNameParameter" },
          { "$ref": "#/parameters/ApiVersionParameter" }
        ],
        "responses": {
          "200": {
            "description": "Successful request for a list of metric alerts",
            "schema": {
              "$ref": "#/definitions/MetricAlertResource"
            },
            "examples": {
              "application/json": {
                "value": [
                  {
                    "location": "global",
                    "tags": {
                      "key1": "value1",
                      "key2": "value2"
                    },
                    "id": "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourcegroups/test/providers/microsoft.insights/metricalerts/storageTest",
                    "name": "storageTest",
                    "properties": {
                      "description": "This is the description of the xstore multidim rule1",
                      "severity": 3,
                      "enabled": true,
                      "scopes": [
                        "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/test/providers/Microsoft.Storage/storageAccounts/testmultidim/blobServices/default"
                      ],
                      "evaluationFrequency": "PT1M",
                      "windowSize": "PT15M",
                      "criteriaSchemaId": "SingleResourceMultipleMetricCriteria",
                      "criteria": {
                        "allOf": [
                          {
                            "name": "HowManyBytes",
                            "metricName": "BlobCapacity",
                            "dimensions": [
                              {
                                "name": "BlobType",
                                "operator": "Include",
                                "values": [
                                  "BlockBlob",
                                  "PageBlob"
                                ]
                              }
                            ],
                            "operator": "GreaterThanOrEqual",
                            "threshold": 5.0,
                            "timeAggregation": "Maximum"
                          }
                        ]
                      },
                      "actions": [
                        {
                          "actionGroupId": "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/test/providers/microsoft.insights/actionGroups/testActionGroup"
                        }
                      ],
                      "currentStatus": {
                        "value": "Healthy",
                        "timestamp": "2018-01-17T20:17:25.6293237Z"
                      }
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "BadRequest",
            "schema": { "$ref": "#/definitions/CloudError" }
          }
        },
        "x-ms-examples": {
          "Get an alert rule": { "$ref": "./examples/getMetricAlert.json" }
        }
      },
      "put": {
        "tags": [ "MetricAlerts" ],
        "description": "Create or update an metric alert definition.",
        "operationId": "MetricAlert_CreateOrUpdate",
        "parameters": [
          { "$ref": "#/parameters/SubscriptionIdParameter" },
          { "$ref": "#/parameters/ResourceGroupNameParameter" },
          { "$ref": "#/parameters/RuleNameParameter" },
          { "$ref": "#/parameters/ApiVersionParameter" },
          {
            "name": "parameters",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/MetricAlertResource"
            },
            "description": "The parameters of the rule to create or update."
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/MetricAlertResource"
            },
            "examples": {
              "application/json": {
                "id": "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/Rac46PostSwapRG/providers/microsoft.insights/metricalerts/chiricutin",
                "name": "chiricutin",
                "type": "Microsoft.Insights/metricalerts",
                "location": "West US",
                "tags": {
                  "hidden-link:/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/Rac46PostSwapRG/providers/Microsoft.Web/sites/leoalerttest": "Resource"
                },
                "properties": {
                  "description": "This is the description of the rule1",
                  "severity": 0,
                  "enabled": true,
                  "scopes": [
                    "/subscriptions/3b7f8a43-4372-4be1-9853-9e51f243d9be/resourceGroups/test/providers/Microsoft.Compute/virtualMachines/testVmLin"
                  ],
                  "evaluationFrequency": "Pt1m",
                  "windowSize": "Pt15m",
                  "templateType": "CorrelatedEvents",
                  "templateSpecificParameters": {
                    "Param1": "Value1",
                    "Param2": "Value2"
                  },
                  "criteriaSchemaId": "SingleREsourceMULTipleMetRICCriteria",
                  "criteria": {
                    "allOf": [
                      {
                        "name": "High_CPU_80",
                        "metricName": "Percentage CPU",
                        "dimensions": [],
                        "operator": "GreaterThan",
                        "threshold": 80.50,
                        "timeAggregation": "Total"
                      },
                      {
                        "name": "High_Disk_50",
                        "metricName": "Disk Write Operations/Sec",
                        "dimensions": [],
                        "operator": "GreaterThanOrEqual",
                        "threshold": 0.55,
                        "timeAggregation": "Maximum"
                      }
                    ]
                  },
                  "actions": [
                    {
                      "actionGroupId": "/subscriptions/3b7f8a43-4372-4be1-9853-9e51f243d9be/resourceGroups/test/providers/microsoft.insights/actionGroups/TestActionGroup",
                      "webhookProperties": {
                        "key01": "value01",
                        "key02": "value02"
                      }
                    }
                  ]
                }
              }
            }
          },
          "default": {
            "description": "BadRequest",
            "schema": { "$ref": "#/definitions/CloudError" }
          }
        },
        "x-ms-examples": {
          "Create or update an alert rule": { "$ref": "./examples/createOrUpdateMetricAlert.json" }
        }
      },
      "patch": {
        "tags": [ "MetricAlerts" ],
        "description": "Update an metric alert definition.",
        "operationId": "MetricAlert_Update",
        "parameters": [
          { "$ref": "#/parameters/SubscriptionIdParameter" },
          { "$ref": "#/parameters/ResourceGroupNameParameter" },
          { "$ref": "#/parameters/RuleNameParameter" },
          { "$ref": "#/parameters/ApiVersionParameter" },
          {
            "name": "parameters",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/MetricAlertResourcePatch"
            },
            "description": "The parameters of the rule to update."
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/MetricAlertResource"
            },
            "examples": {
              "application/json": {
                "id": "/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/Rac46PostSwapRG/providers/microsoft.insights/metricalerts/chiricutin",
                "name": "chiricutin",
                "type": "Microsoft.Insights/metricalerts",
                "location": "West US",
                "tags": {
                  "hidden-link:/subscriptions/b67f7fec-69fc-4974-9099-a26bd6ffeda3/resourceGroups/Rac46PostSwapRG/providers/Microsoft.Web/sites/leoalerttest": "Resource"
                },
                "properties": {
                  "description": "This is the description of the rule1",
                  "severity": 0,
                  "enabled": true,
                  "scopes": [
                    "/subscriptions/3b7f8a43-4372-4be1-9853-9e51f243d9be/resourceGroups/test/providers/Microsoft.Compute/virtualMachines/testVmLin"
                  ],
                  "evaluationFrequency": "Pt1m",
                  "windowSize": "Pt15m",
                  "templateType": "CorrelatedEvents",
                  "templateSpecificParameters": {
                    "Param1": "Value1",
                    "Param2": "Value2"
                  },
                  "criteriaSchemaId": "SingleREsourceMULTipleMetRICCriteria",
                  "criteria": {
                    "allOf": [
                      {
                        "name": "High_CPU_80",
                        "metricName": "Percentage CPU",
                        "dimensions": [],
                        "operator": "GreaterThan",
                        "threshold": 80.50,
                        "timeAggregation": "Total"
                      },
                      {
                        "name": "High_Disk_50",
                        "metricName": "Disk Write Operations/Sec",
                        "dimensions": [],
                        "operator": "GreaterThanOrEqual",
                        "threshold": 0.55,
                        "timeAggregation": "Maximum"
                      }
                    ]
                  },
                  "actions": [
                    {
                      "actionGroupId": "/subscriptions/3b7f8a43-4372-4be1-9853-9e51f243d9be/resourceGroups/test/providers/microsoft.insights/actionGroups/TestActionGroup",
                      "webhookProperties": {
                        "key01": "value01",
                        "key02": "value02"
                      }
                    }
                  ]
                }
              }
            }
          },
          "default": {
            "description": "BadRequest",
            "schema": { "$ref": "#/definitions/CloudError" }
          }
        },
        "x-ms-examples": {
          "Create or update an alert rule": { "$ref": "./examples/UpdateMetricAlert.json" }
        }
      },
      "delete": {
        "tags": [ "MetricAlerts" ],
        "description": "Delete an alert rule defitiniton.",
        "operationId": "MetricAlert_Delete",
        "parameters": [
          { "$ref": "#/parameters/SubscriptionIdParameter" },
          { "$ref": "#/parameters/ResourceGroupNameParameter" },
          { "$ref": "#/parameters/RuleNameParameter" },
          { "$ref": "#/parameters/ApiVersionParameter" }
        ],
        "responses": {
          "204": {
            "description": "No content: the request was successful, but the response is empty"
          },
          "200": {
            "description": "Successful request to delete an metric alert rule"
          }
        },
        "x-ms-examples": {
          "Delete an alert rule": { "$ref": "./examples/deleteMetricAlert.json" }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insight/metricAlerts/{ruleName}/status": {
      "get": {
        "tags": [ "MetricAlertsStatus" ],
        "description": "Retrieve an alert rule status.",
        "operationId": "MetricAlertsStatus_List",
        "parameters": [
          { "$ref": "#/parameters/SubscriptionIdParameter" },
          { "$ref": "#/parameters/ResourceGroupNameParameter" },
          { "$ref": "#/parameters/RuleNameParameter" },
          { "$ref": "#/parameters/ApiVersionParameter" }
        ],
        "responses": {
          "200": {
            "description": "Successful request for a list of metric alerts",
            "schema": {
              "$ref": "#/definitions/MetricAlertStatusCollection"
            },
            "examples": {
              "application/json": {
                "value": [
                  {
                    "id": "/subscriptions/009f6022-67ec-423e-9aa7-691182870588/resourceGroups/EastUs/providers/microsoft.insights/metricAlerts/LeoAlert_custom1",
                    "name": "cmVzb3VyY2VJZD0vc3Vic2NyaXB0aW9ucy8xNGRkZjBjNS03N2M1LTRiNTMtODRmNi1lMWZhNDNhZDY4ZjcvcmVzb3VyY2VHcm91cHMvZ2lndGVzdC9wcm92aWRlcnMvTWljcm9zb2Z0LkNvbXB1dGUvdmlydHVhbE1hY2hpbmVzL2dpZ3dhZG1l",
                    "type": "Microsoft.Insights/metricAlerts/status",
                    "properties": {
                      "dimensions": {
                        "resourceId": "/subscriptions/14ddf0c5-77c5-4b53-84f6-e1fa43ad68f7/resourceGroups/gigtest/providers/Microsoft.Compute/virtualMachines/gigwadme"
                      },
                      "status": "Healthy",
                      "timestamp": "2018-01-17T20:17:25.6293237Z"
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "BadRequest",
            "schema": { "$ref": "#/definitions/CloudError" }
          }
        },
        "x-ms-examples": {
          "Get an alert rule status": { "$ref": "./examples/getMetricAlertStatus.json" }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insight/metricAlerts/{ruleName}/status/{statusName}": {
      "get": {
        "tags": [ "MetricAlertsStatus" ],
        "description": "Retrieve an alert rule status.",
        "operationId": "MetricAlertsStatus_listByName",
        "parameters": [
          { "$ref": "#/parameters/SubscriptionIdParameter" },
          { "$ref": "#/parameters/ResourceGroupNameParameter" },
          { "$ref": "#/parameters/RuleNameParameter" },
          { "$ref": "#/parameters/StatusNameParameter" },
          { "$ref": "#/parameters/ApiVersionParameter" }
        ],
        "responses": {
          "200": {
            "description": "Successful request for a list of metric alerts",
            "schema": {
              "$ref": "#/definitions/MetricAlertStatusCollection"
            },
            "examples": {
              "application/json": {
                "value": [
                  {
                    "id": "/subscriptions/009f6022-67ec-423e-9aa7-691182870588/resourceGroups/EastUs/providers/microsoft.insights/metricAlerts/LeoAlert_custom1",
                    "name": "cmVzb3VyY2VJZD0vc3Vic2NyaXB0aW9ucy8xNGRkZjBjNS03N2M1LTRiNTMtODRmNi1lMWZhNDNhZDY4ZjcvcmVzb3VyY2VHcm91cHMvZ2lndGVzdC9wcm92aWRlcnMvTWljcm9zb2Z0LkNvbXB1dGUvdmlydHVhbE1hY2hpbmVzL2dpZ3dhZG1l",
                    "type": "Microsoft.Insights/metricAlerts/status",
                    "properties": {
                      "dimensions": {
                        "resourceId": "/subscriptions/14ddf0c5-77c5-4b53-84f6-e1fa43ad68f7/resourceGroups/gigtest/providers/Microsoft.Compute/virtualMachines/gigwadme"
                      },
                      "status": "Healthy",
                      "timestamp": "2018-01-17T20:17:25.6293237Z"
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "BadRequest",
            "schema": { "$ref": "#/definitions/CloudError" }
          }
        },
        "x-ms-examples": {
          "Get an alert rule status": { "$ref": "./examples/getMetricAlertStatusByName.json" }
        }
      }
    }
  },
  "definitions": {
    "Resource": {
      "properties": {
        "id": {
          "type": "string",
          "readOnly": true,
          "description": "Azure resource Id"
        },
        "name": {
          "type": "string",
          "readOnly": true,
          "description": "Azure resource name"
        },
        "type": {
          "type": "string",
          "readOnly": true,
          "description": "Azure resource type"
        },
        "location": {
          "type": "string",
          "description": "Resource location",
          "x-ms-mutability": [
            "create",
            "read"
          ]
        },
        "tags": {
          "additionalProperties": {
            "type": "string"
          },
          "description": "Resource tags"
        }
      },
      "required": [
        "location"
      ],
      "x-ms-azure-resource": true,
      "description": "An azure resource object"
    },
    "Action": {
      "description": "An alert action.",
      "properties": {
        "actionGroupId": {
          "type": "string",
          "description": "the id of the action group to use."
        },
        "webhookProperties": {
          "type": "object",
          "additionalProperties": {
            "type": "string",
            "description": "the dictionary of custom properties to include with the post operation. These data are appended to the webhook payload."
          }
        }
      }
    },
    "AlertStatus": {
      "description": "An alert status.",
      "properties": {
        "value": {
          "type": "string",
          "description": "status value"
        },
        "timestamp": {
          "type": "string",
          "description": "UTC time when the status was checked."
        }
      }
    },
    "MetricAlertProperties": {
      "required": [
        "enabled",
        "description",
        "severity",
        "evaluationFrequency",
        "windowSize",
        "criteriaSchemaId",
        "criteria"
      ],
      "properties": {
        "description": {
          "type": "string",
          "description": "the description of the metric alert that will be included in the alert email."
        },
        "severity": {
          "type": "integer",
          "description": "Alert severity {0, 1, 2, 3, 4}"
        },
        "enabled": {
          "type": "boolean",
          "description": "the flag that indicates whether the metric alert is enabled."
        },
        "scopes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "the list of resource id's that this metric alert is scoped to."
        },
        "evaluationFrequency": {
          "type": "string",
          "format": "duration",
          "description": "how often the metric alert is evaluated represented in ISO 8601 duration format."
        },
        "windowSize": {
          "type": "string",
          "format": "duration",
          "description": "the period of time (in ISO 8601 duration format) that is used to monitor alert activity based on the threshold."
        },
        "criteriaSchemaId": {
          "type": "string",
          "description": "schema to use to interpret the criteria JSON."
        },
        "criteria": {
          "type": "string",
          "description": "json data that follows the schema defined by criteria schema id."
        },
        "actions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Action"
          },
          "description": "the array of actions that are performed when the alert rule becomes active, and when an alert condition is resolved."
        },
        "currentStatus": {
          "readOnly": true,
          "$ref": "#/definitions/AlertStatus",
          "description": "the current metric alert status."
        },
        "lastUpdatedTime": {
          "readOnly": true,
          "type": "string",
          "format": "date-time",
          "description": "Last time the rule was updated in ISO8601 format."
        }
      },
      "description": "An alert rule."
    },
    "MetricAlertResource": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        }
      ],
      "required": [
        "properties"
      ],
      "properties": {
        "properties": {
          "x-ms-client-flatten": true,
          "$ref": "#/definitions/MetricAlertProperties",
          "description": "The alert rule properties of the resource."
        }
      },
      "description": "The metric alert resource."
    },
    "MetricAlertResourcePatch": {
      "properties": {
        "tags": {
          "additionalProperties": {
            "type": "string"
          },
          "description": "Resource tags"
        },
        "properties": {
          "x-ms-client-flatten": true,
          "$ref": "#/definitions/MetricAlertProperties",
          "description": "The alert rule properties of the resource."
        }
      },
      "description": "The metric alert resource for patch operations."
    },
    "MetricAlertResourceCollection": {
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/MetricAlertResource"
          },
          "description": "the values for the alert rule resources."
        }
      },
      "description": "Represents a collection of alert rule resources."
    },
    "MetricAlertStatusCollection": {
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/MetricAlertStatus"
          },
          "description": "the values for the alert rule resources."
        }
      },
      "description": "Represents a collection of alert rule resources."
    },
    "MetricAlertStatusProperties": {
      "description": "An alert status properties.",
      "properties": {
        "dimensions": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "status": {
          "type": "string",
          "description": "status value"
        },
        "timestamp": {
          "type": "string",
          "description": "UTC time when the status was checked."
        }
      }
    },
    "MetricAlertStatus": {
      "description": "An alert status.",
      "properties": {
        "name": {
          "type": "string",
          "description": "The status name."
        },
        "id": {
          "type": "string",
          "description": "The alert rule arm id."
        },
        "type": {
          "type": "string",
          "enum": [
            "microsoft.insights/metricalerts/status"
          ]
        },
        "properties": {
          "x-ms-client-flatten": true,
          "$ref": "#/definitions/MetricAlertStatus",
          "description": "The alert status properties of the metric alert status."
        }
      }
    },
    "CloudError": {
      "description": "Error from a REST request.",
      "type": "object",
      "properties": { "error": { "$ref": "#/definitions/CloudErrorBody" } },
      "x-ms-external": true
    },
    "CloudErrorBody": {
      "description": "Body of an error from a REST request.",
      "type": "object",
      "properties": {
        "code": { "type": "string" },
        "message": { "type": "string" },
        "target": { "type": "string" },
        "details": {
          "description": "Inner errors.",
          "type": "array",
          "items": { "$ref": "#/definitions/CloudErrorBody" }
        }
      },
      "x-ms-external": true
    }
  },
  "parameters": {
    "SubscriptionIdParameter": {
      "name": "subscriptionId",
      "in": "path",
      "required": true,
      "type": "string",
      "description": "The Azure subscription Id."
    },
    "ApiVersionParameter": {
      "name": "api-version",
      "in": "query",
      "required": true,
      "type": "string",
      "description": "Client Api Version."
    },
    "ResourceGroupNameParameter": {
      "name": "resourceGroupName",
      "in": "path",
      "required": true,
      "type": "string",
      "description": "The name of the resource group.",
      "x-ms-parameter-location": "method"
    },
    "RuleNameParameter": {
      "name": "ruleName",
      "in": "path",
      "required": true,
      "type": "string",
      "description": "The name of the rule.",
      "x-ms-parameter-location": "method"
    },
    "StatusNameParameter": {
      "name": "statusName",
      "in": "path",
      "required": true,
      "type": "string",
      "description": "The name of the status.",
      "x-ms-parameter-location": "method"
    }
  }
}
