{
  "swagger": "2.0",
  "info": {
    "description": "V2 API definition for the Azure Container Registry runtime",
    "version": "2018-08-10-preview",
    "title": "Azure Container Registry"
  },
  "host": "acrapi.azurecr-test.io",
  "tags": [
    {
      "name": "v2",
      "description": "Root API"
    },
    {
      "name": "Manifest",
      "description": "Everything about manifests"
    },
    {
      "name": "Tag",
      "description": "Everything about tags"
    },
    {
      "name": "Layer",
      "description": "Everything about layers"
    },
    {
      "name": "Repository",
      "description": "Everything about repository"
    },
    {
      "name": "AcrRepository",
      "description": "ACR APIs related to repositories"
    },
    {
      "name": "AcrManifest",
      "description": "ACR APIs related to manifests"
    },
    {
      "name": "AcrTag",
      "description": "ACR APIs related to tags"
    }
  ],
  "schemes": [
    "https"
  ],
  "security": [
    {
      "registry_auth": []
    }
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v2/": {
      "get": {
        "tags": [
          "v2"
        ],
        "description": "Tells whether this Docker Registry instance supports Docker Registry HTTP API v2",
        "x-ms-examples": {
          "Check Docker Registry V2 Support": {
            "$ref": "./examples/GetDockerRegistryV2Support.json"
          }
        },
        "operationId": "GetDockerRegistryV2Support",
        "responses": {
          "200": {
            "description": "Successful response. API v2 supported"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/v2/{name}/tags/list": {
      "get": {
        "tags": [
          "Tag"
        ],
        "description": "Fetch the tags under the repository identified by 'name'",
        "x-ms-examples": {
          "List tags": {
            "$ref": "./examples/GetTagList.json"
          }
        },
        "operationId": "GetTagList",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Gives a list of tags for the names repository.",
            "schema": {
              "$ref": "#/definitions/RepositoryTags"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/v2/{name}/manifests/{reference}": {
      "get": {
        "tags": [
          "Manifest"
        ],
        "description": "Pulls the image manifest file associated with the specified name and reference. Reference may be a tag or a digest",
        "x-ms-examples": {
          "Get manifest": {
            "$ref": "./examples/GetManifest.json"
          }
        },
        "operationId": "GetManifest",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "reference",
            "in": "path",
            "description": "A tag or a digest, pointing to a specific image",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the requested manifest file",
            "schema": {
              "$ref": "#/definitions/Manifest"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/v2/_catalog": {
      "get": {
        "tags": [
          "Repository"
        ],
        "description": "List repositories",
        "operationId": "GetRepositories",
        "x-ms-examples": {
          "Get repositories in a registry": {
            "$ref": "./examples/GetRepositories.json"
          }
        },
        "parameters": [
          {
            "name": "last",
            "in": "query",
            "description": "query parameter for the last item in previous query",
            "required": false,
            "type": "string"
          },
          {
            "name": "n",
            "in": "query",
            "description": "query parameter for max number of items",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a list of repositories",
            "schema": {
              "$ref": "#/definitions/Repositories"
            }
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/acr/v1/_catalog": {
      "get": {
        "tags": [
          "AcrRepository"
        ],
        "description": "List repositories",
        "operationId": "GetAcrRepositories",
        "x-ms-examples": {
          "Get repositories in a registry": {
            "$ref": "./examples/GetRepositories.json"
          }
        },
        "parameters": [
          {
            "name": "last",
            "in": "query",
            "description": "query parameter for the last item in previous query",
            "required": false,
            "type": "string"
          },
          {
            "name": "n",
            "in": "query",
            "description": "query parameter for max number of items",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a list of repositories",
            "schema": {
              "$ref": "#/definitions/Repositories"
            }
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/acr/v1/{name}": {
      "get": {
        "tags": [
          "AcrRepository",
          "AcrMetadata"
        ],
        "description": "Get repository attributes",
        "operationId": "GetAcrRepositoryAttributes",
        "x-ms-examples": {
          "Get details of repository": {
            "$ref": "./examples/GetAcrRepositoryAttributes.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a list of attributes",
            "schema": {
              "$ref": "#/definitions/RepositoryAttributes"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "AcrRepository"
        ],
        "description": "Delete a repository",
        "operationId": "DeleteAcrRepository",
        "x-ms-examples": {
          "Delete a repository": {
            "$ref": "./examples/DeleteAcrRepository.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "202": {
            "description": "The repository is deleted",
            "schema": {
              "$ref": "#/definitions/DeletedRepository"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      },
      "patch": {
        "tags": [
          "AcrRepository",
          "AcrMetadata"
        ],
        "description": "Update attributes of a repository",
        "operationId": "UpdateAcrRepositoryAttributes",
        "x-ms-examples": {
          "Update repository attributes": {
            "$ref": "./examples/UpdateAcrRepository.json"
          }
        },
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "in": "body",
            "description": "Repository attribute value",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ChangeableAttributes"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The attributes is updated"
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/acr/v1/{name}/_tags": {
      "get": {
        "tags": [
          "AcrTag",
          "AcrMetadata"
        ],
        "description": "List tags of a repository",
        "operationId": "GetAcrTags",
        "x-ms-examples": {
          "Get tags of a repository": {
            "$ref": "./examples/GetAcrTags.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "last",
            "in": "query",
            "description": "query parameter for the last item in previous query",
            "required": false,
            "type": "string"
          },
          {
            "name": "n",
            "in": "query",
            "description": "query parameter for max number of items",
            "required": false,
            "type": "string"
          },
          {
            "name": "orderby",
            "in": "query",
            "description": "orderby query parameter",
            "required": false,
            "type": "string"
          },
          {
            "name": "digest",
            "in": "query",
            "description": "filter by digest",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Tag details of a repository",
            "schema": {
              "$ref": "#/definitions/AcrRepositoryTags"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/acr/v1/{name}/_tags/{reference}": {
      "get": {
        "tags": [
          "AcrTag",
          "AcrMetadata"
        ],
        "description": "Get manifest attributes by tag",
        "operationId": "GetAcrTagAttributes",
        "x-ms-examples": {
          "Get manifest attributes": {
            "$ref": "./examples/GetAcrTagAttributes.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "reference",
            "in": "path",
            "description": "A tag name of the image",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Tag attributes",
            "schema": {
              "$ref": "#/definitions/AcrTagAttributes"
            }
          },
          "404": {
            "description": "Tag doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      },
      "patch": {
        "tags": [
          "AcrTag",
          "AcrMetadata"
        ],
        "description": "Update tag attributes",
        "operationId": "UpdateAcrTagAttributes",
        "consumes": [
          "application/json"
        ],
        "x-ms-examples": {
          "Update attributes of a manifest": {
            "$ref": "./examples/UpdateAcrTagAttributes.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "reference",
            "in": "path",
            "description": "A tag name of the image",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "value",
            "description": "Changeable attribute value",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ChangeableAttributes"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The attributes are updated"
          },
          "404": {
            "description": "Manifest doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "AcrTag",
          "AcrMetadata"
        ],
        "description": "Delete tag",
        "operationId": "DeleteAcrTag",
        "consumes": [
          "application/json"
        ],
        "x-ms-examples": {
          "Update attributes of a manifest": {
            "$ref": "./examples/DeleteAcrTag.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "reference",
            "in": "path",
            "description": "A tag name of the image",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "The tag is deleted"
          },
          "404": {
            "description": "Tag doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/acr/v1/{name}/_manifests": {
      "get": {
        "tags": [
          "AcrManifest",
          "AcrMetadata"
        ],
        "description": "List manifests of a repository",
        "operationId": "GetAcrManifests",
        "x-ms-examples": {
          "Get details of repository": {
            "$ref": "./examples/GetAcrManifests.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "last",
            "in": "query",
            "description": "query parameter for the last item in previous query",
            "required": false,
            "type": "string"
          },
          {
            "name": "n",
            "in": "query",
            "description": "query parameter for max number of items",
            "required": false,
            "type": "string"
          },
          {
            "name": "orderby",
            "in": "query",
            "description": "orderby query parameter",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a list of manifests",
            "schema": {
              "$ref": "#/definitions/AcrManifests"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    },
    "/acr/v1/{name}/_manifests/{reference}": {
      "get": {
        "tags": [
          "AcrManifest",
          "AcrMetadata"
        ],
        "description": "Get manifest attributes",
        "operationId": "GetAcrManifestAttributes",
        "x-ms-examples": {
          "Get manifest attributes": {
            "$ref": "./examples/GetAcrManifestAttributes.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "reference",
            "in": "path",
            "description": "A digest pointing to a specific image",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "List of attributes",
            "schema": {
              "$ref": "#/definitions/AcrManifestAttributes"
            }
          },
          "404": {
            "description": "Manifest doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      },
      "patch": {
        "tags": [
          "AcrManifest",
          "AcrMetadata"
        ],
        "description": "Update attributes of a manifest",
        "operationId": "UpdateAcrManifestAttributes",
        "consumes": [
          "application/json"
        ],
        "x-ms-examples": {
          "Update attributes of a manifest": {
            "$ref": "./examples/UpdateAcrManifestAttributes.json"
          }
        },
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "Name of the image (including the namespace)",
            "required": true,
            "type": "string"
          },
          {
            "name": "reference",
            "in": "path",
            "description": "A tag or a digest, pointing to a specific image",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "value",
            "description": "Changeable attribute value",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ChangeableAttributes"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The attributes are updated"
          },
          "404": {
            "description": "Manifest doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "registry_auth": {
      "type": "basic"
    }
  },
  "definitions": {
    "RepositoryAttributes": {
      "type": "object",
      "description": "Repository attributes",
      "properties": {
        "registry": {
          "type": "string",
          "description": "Registry name"
        },
        "imageName": {
          "type": "string",
          "description": "Image name"
        },
        "createdTime": {
          "type": "string",
          "description": "Image created time"
        },
        "lastUpdateTime": {
          "type": "string",
          "description": "Image last update time"
        },
        "manifestCount": {
          "type": "number",
          "description": "Number of the manifests"
        },
        "tagCount": {
          "type": "number",
          "description": "Number of the tags"
        },
        "changeableAttributes": {
          "description": "Changeable attributes",
          "$ref": "#/definitions/ChangeableAttributes"
        }
      },
      "example": {
        "registry": "registryname.azurecr.io",
        "changeableAttributes": {
          "readEnabled": true,
          "listEnabled": true,
          "deleteEnabled": true,
          "writeEnabled": true
        },
        "imageName": "imageName",
        "createdTime": "2018-09-07T16:30:46.6583219Z",
        "tagCount": 6,
        "manifestCount": 2,
        "lastUpdateTime": "2018-09-07T16:30:46.6583219Z"
      }
    },
    "AcrRepositoryTags": {
      "description": "List of tag details",
      "properties": {
        "registry": {
          "type": "string",
          "description": "Registry name"
        },
        "imageName": {
          "type": "string",
          "description": "Image name"
        },
        "tags": {
          "type": "array",
          "x-ms-client-name": "TagsAttributes",
          "description": "List of tag attribute details",
          "items": {
            "$ref": "#/definitions/AcrTagAttributesBase"
          }
        }
      },
      "example": {
        "registry": "registry",
        "imageName": "imageName",
        "tags": [
          {
            "changeableAttributes": {
              "readEnabled": true,
              "listEnabled": true,
              "deleteEnabled": true,
              "writeEnabled": true
            },
            "name": "name",
            "digest": "digest",
            "createdTime": "createdTime",
            "signed": true,
            "quarantineState": "quarantineState",
            "lastUpdateTime": "lastUpdateTime"
          },
          {
            "changeableAttributes": {
              "readEnabled": true,
              "listEnabled": true,
              "deleteEnabled": true,
              "writeEnabled": true
            },
            "name": "name",
            "digest": "digest",
            "createdTime": "createdTime",
            "signed": true,
            "quarantineState": "quarantineState",
            "lastUpdateTime": "lastUpdateTime"
          }
        ]
      }
    },
    "AcrTagAttributes": {
      "description": "Tag attributes",
      "properties": {
        "registry": {
          "type": "string",
          "description": "Registry name"
        },
        "imageName": {
          "type": "string",
          "description": "Image name"
        },
        "tag": {
          "x-ms-client-name": "TagAttributes",
          "description": "List of tag attribute details",
          "$ref": "#/definitions/AcrTagAttributesBase"
        }
      },
      "example": {
        "registry": "registry",
        "imageName": "imageName",
        "tag": {
          "changeableAttributes": {
            "readEnabled": true,
            "listEnabled": true,
            "deleteEnabled": true,
            "writeEnabled": true
          },
          "name": "name",
          "digest": "digest",
          "createdTime": "createdTime",
          "signed": true,
          "quarantineState": "quarantineState",
          "lastUpdateTime": "lastUpdateTime"
        }
      }
    },
    "TagAttributes": {
      "description": "Tag attributes",
      "properties": {
        "registry": {
          "description": "Registry name",
          "type": "string"
        },
        "imageName": {
          "description": "Image name",
          "type": "string"
        },
        "tag": {
          "$ref": "#/definitions/TagAttributes_tag",
          "description": "Tag attributes"
        }
      },
      "example": {
        "registry": "registry",
        "imageName": "imageName",
        "tag": {
          "signatureRecord": "signatureRecord"
        }
      }
    },
    "AcrTagAttributesBase": {
      "description": "Tag attribute details",
      "properties": {
        "name": {
          "type": "string",
          "description": "Tag name"
        },
        "digest": {
          "type": "string",
          "description": "Tag digest"
        },
        "createdTime": {
          "type": "string",
          "description": "Tag created time"
        },
        "lastUpdateTime": {
          "type": "string",
          "description": "Tag last update time"
        },
        "signed": {
          "type": "boolean",
          "description": "Is signed"
        },
        "changeableAttributes": {
          "$ref": "#/definitions/ChangeableAttributes",
          "description": "Changeable attributes"
        }
      },
      "example": {
        "changeableAttributes": {
          "readEnabled": true,
          "listEnabled": true,
          "deleteEnabled": true,
          "writeEnabled": true
        },
        "name": "tagname",
        "digest": "sha256:0873c923e00e0fd2ba78041bfb64a105e1ecb7678916d1f7776311e45bf5634b",
        "createdTime": "2018-08-10T17:28:44.1082945Z",
        "signed": true,
        "lastUpdateTime": "2018-08-10T17:28:44.1082945Z"
      }
    },
    "AcrManifests": {
      "description": "Manifest attributes",
      "properties": {
        "registry": {
          "type": "string",
          "description": "Registry name"
        },
        "imageName": {
          "type": "string",
          "description": "Image name"
        },
        "manifests": {
          "type": "array",
          "description": "List of manifests",
          "items": {
            "$ref": "#/definitions/AcrManifestAttributesBase",
            "description": "Manifest details"
          }
        }
      },
      "example": {
        "registry": "registry",
        "imageName": "imageName",
        "manifests": [
          {
            "changeableAttributes": {
              "quarantineDetails": "quarantineDetails",
              "readEnabled": true,
              "quarantineState": "quarantineState",
              "listEnabled": true,
              "deleteEnabled": true,
              "writeEnabled": true
            },
            "os": "os",
            "digest": "digest",
            "createdTime": "createdTime",
            "mediaType": "mediaType",
            "lastUpdateTime": "lastUpdateTime",
            "architecture": "architecture",
            "tags": [
              "tags",
              "tags"
            ]
          },
          {
            "changeableAttributes": {
              "quarantineDetails": "quarantineDetails",
              "readEnabled": true,
              "quarantineState": "quarantineState",
              "listEnabled": true,
              "deleteEnabled": true,
              "writeEnabled": true
            },
            "os": "os",
            "digest": "digest",
            "createdTime": "createdTime",
            "mediaType": "mediaType",
            "lastUpdateTime": "lastUpdateTime",
            "architecture": "architecture",
            "tags": [
              "tags",
              "tags"
            ]
          }
        ]
      }
    },
    "AcrManifestAttributes": {
      "description": "Manifest attributes details",
      "properties": {
        "registry": {
          "description": "Registry name",
          "type": "string"
        },
        "imageName": {
          "description": "Image name",
          "type": "string"
        },
        "manifest": {
          "description": "Manifest attributes",
          "$ref": "#/definitions/AcrManifestAttributesBase"
        }
      },
      "example": {
        "registry": "acrapi.azurecr-test.io",
        "imageName": "nanoserver",
        "manifest": {
          "digest": "sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086",
          "createdTime": "2018-09-06T06:17:20.9983915Z",
          "lastUpdateTime": "2018-09-06T06:17:20.9983915Z",
          "architecture": "amd64",
          "os": "windows",
          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
          "tags": [
            "4.7.2-20180905-nanoserver-1803"
          ],
          "changeableAttributes": {
            "deleteEnabled": true,
            "writeEnabled": true,
            "readEnabled": true,
            "listEnabled": true
          }
        }
      }
    },
    "AcrManifestAttributesBase": {
      "type": "object",
      "description": "Manifest details",
      "properties": {
        "digest": {
          "type": "string",
          "description": "Manifest digest"
        },
        "createdTime": {
          "type": "string",
          "description": "Created time"
        },
        "lastUpdateTime": {
          "type": "string",
          "description": "Last update time"
        },
        "architecture": {
          "type": "string",
          "description": "CPU architecture"
        },
        "os": {
          "type": "string",
          "description": "Operating system"
        },
        "mediaType": {
          "type": "string",
          "description": "Media type"
        },
        "tags": {
          "type": "array",
          "description": "List of tags",
          "items": {
            "type": "string",
            "description": "Tag name"
          }
        },
        "changeableAttributes": {
          "$ref": "#/definitions/ChangeableAttributes",
          "description": "Changeable attributes"
        }
      },
      "example": {
        "changeableAttributes": {
          "readEnabled": true,
          "listEnabled": true,
          "deleteEnabled": true,
          "writeEnabled": true
        },
        "os": "os",
        "digest": "digest",
        "createdTime": "createdTime",
        "mediaType": "mediaType",
        "lastUpdateTime": "lastUpdateTime",
        "architecture": "architecture",
        "tags": [
          "tags",
          "tags"
        ]
      }
    },
    "AcrErrors": {
      "description": "Acr error response describing why the operation failed",
      "properties": {
        "errors": {
          "type": "array",
          "description": "Array of detailed error",
          "items": {
            "$ref": "#/definitions/AcrErrorInfo"
          }
        }
      }
    },
    "RepositoryTags": {
      "description": "Result of the request to list tags of the image",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the image"
        },
        "tags": {
          "type": "array",
          "description": "List of tags",
          "items": {
            "type": "string",
            "description": "Tag name"
          }
        }
      },
      "example": {
        "name": "name",
        "tags": [
          "tags",
          "tags"
        ]
      }
    },
    "Manifest": {
      "description": "Returns the requested manifest file",
      "properties": {
        "schemaVersion": {
          "type": "number",
          "description": "Schema version"
        },
        "architecture": {
          "type": "string",
          "description": "CPU architecture"
        },
        "name": {
          "type": "string",
          "description": "Image name"
        },
        "tag": {
          "type": "string",
          "description": "Image tag"
        },
        "fsLayers": {
          "type": "array",
          "description": "List of layer information",
          "items": {
            "$ref": "#/definitions/ImageLayer"
          }
        },
        "history": {
          "type": "array",
          "description": "Image history",
          "x-ms-client-name": "ImageHistories",
          "items": {
            "$ref": "#/definitions/ImageHistory"
          }
        },
        "signatures": {
          "type": "array",
          "description": "Image signature",
          "items": {
            "$ref": "#/definitions/ImageSignature"
          }
        }
      },
      "example": {
        "name": "name",
        "tag": "tag",
        "fsLayers": [
          {
            "blobSum": "sha256:1f7d468f830cb0ed4beb8edc9438f18096e8c682e56a35242f60e6c61b718b30"
          },
          {
            "blobSum": "sha256:2f7d468f830cb0ed4beb8edc9438f18096e8c682e56a35242f60e6c61b718b31"
          }
        ],
        "history": "history",
        "signatures": [
          {
            "header": {
              "jwk": {
                "crv": "P-256",
                "kid": "WGXM:EYWQ:DA53:LQUP:BCWG:5RDG:S3ZM:ETH7:VMQS:WWKZ:EWDG:V74Q",
                "kty": "EC",
                "x": "OxZ9k5BVjPZ7jb3BmBD4X0d8MVPJqfF4NeSe8reoqnY",
                "y": "EaCqTe4-vYwhk7qU6Bs2-AeLGOVtCe_-IY2MdE0Vfyc"
              },
              "alg": "ES256"
            },
            "signature": "p73LfotMGD8nNXz2g9YX2XtSllb4GI5-b3vjqP5N0nkv8QXg-r5z_omGiVbOZE2BYG1X_4TIN23l1KSEqsXxOg",
            "protected": "eyJmb3JtYXRMZW5ndGgiOjI5ODYsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxOC0wOS0yMFQyMzo0MTo1MloifQ"
          }
        ]
      }
    },
    "ImageSignature": {
      "description": "Signature of a signed manifest",
      "properties": {
        "header": {
          "description": "A JSON web signature",
          "$ref": "#/definitions/JWK"
        },
        "signature": {
          "type": "string",
          "description": "A signature for the image manifest, signed by a libtrust private key"
        },
        "protected": {
          "type": "string",
          "x-ms-client-name": "protectedHeader",
          "description": "The signed protected header"
        }
      },
      "example": {
        "header": {
          "jwk": {
            "crv": "P-256",
            "kid": "WGXM:EYWQ:DA53:LQUP:BCWG:5RDG:S3ZM:ETH7:VMQS:WWKZ:EWDG:V74Q",
            "kty": "EC",
            "x": "OxZ9k5BVjPZ7jb3BmBD4X0d8MVPJqfF4NeSe8reoqnY",
            "y": "EaCqTe4-vYwhk7qU6Bs2-AeLGOVtCe_-IY2MdE0Vfyc"
          },
          "alg": "ES256"
        },
        "signature": "p73LfotMGD8nNXz2g9YX2XtSllb4GI5-b3vjqP5N0nkv8QXg-r5z_omGiVbOZE2BYG1X_4TIN23l1KSEqsXxOg",
        "protected": "eyJmb3JtYXRMZW5ndGgiOjI5ODYsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxOC0wOS0yMFQyMzo0MTo1MloifQ"
      }
    },
    "JWK": {
      "description": "A JSON web signature",
      "properties": {
        "jwk": {
          "$ref": "#/definitions/JWKHeader"
        },
        "alg": {
          "type": "string",
          "description": "The algorithm used to sign or encrypt the JWT"
        }
      }
    },
    "JWKHeader": {
      "description": "JSON web key parameter",
      "properties": {
        "crv": {
          "type": "string",
          "description": "crv value"
        },
        "kid": {
          "type": "string",
          "description": "kid value"
        },
        "kty": {
          "type": "string",
          "description": "kty value"
        },
        "x": {
          "type": "string",
          "description": "x value"
        },
        "y": {
          "type": "string",
          "description": "y value"
        }
      }
    },
    "ImageHistory": {
      "description": "A list of unstructured historical data for v1 compatibility",
      "properties": {
        "v1Compatibility": {
          "type": "string",
          "description": "The raw v1 compatibility information"
        }
      },
      "example": {
        "v1Compatibility": "v1 compatibility info"
      }
    },
    "Repositories": {
      "description": "List of repositories",
      "properties": {
        "repositories": {
          "type": "array",
          "x-ms-client-name": "Names",
          "description": "Repository names",
          "items": {
            "type": "string"
          }
        }
      },
      "example": {
        "repositories": [
          "production/alpine",
          "testing/alpine"
        ]
      }
    },
    "DeletedRepository": {
      "description": "Deleted repository",
      "properties": {
        "manifestsDeleted": {
          "type": "array",
          "description": "SHA of the deleted image",
          "items": {
            "type": "string"
          }
        },
        "tagsDeleted": {
          "type": "array",
          "description": "Tag of the deleted image",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "AcrErrorInfo": {
      "description": "Error information",
      "properties": {
        "code": {
          "description": "Error code",
          "type": "string"
        },
        "message": {
          "type": "string",
          "description": "Error message"
        },
        "detail": {
          "type": "string",
          "description": "Error details"
        }
      }
    },
    "ImageLayer": {
      "description": "Image layer information",
      "properties": {
        "blobSum": {
          "type": "string",
          "description": "SHA of an image layer"
        }
      },
      "example": {
        "blobSum": "sha256:1f7d468f830cb0ed4beb8edc9438f18096e8c682e56a35242f60e6c61b718b30"
      }
    },
    "ChangeableAttributes": {
      "properties": {
        "deleteEnabled": {
          "type": "boolean",
          "description": "Delete enabled"
        },
        "writeEnabled": {
          "type": "boolean",
          "description": "Write enabled"
        },
        "listEnabled": {
          "type": "boolean",
          "description": "List enabled"
        },
        "readEnabled": {
          "type": "boolean",
          "description": "Read enabled"
        }
      },
      "example": {
        "readEnabled": true,
        "listEnabled": true,
        "deleteEnabled": true,
        "writeEnabled": true
      }
    },
    "TagAttributes_tag": {
      "description": "Tag",
      "properties": {
        "signatureRecord": {
          "description": "SignatureRecord value",
          "type": "string"
        }
      },
      "example": {
        "signatureRecord": "signatureRecord"
      }
    },
    "ManifestAttributes_manifest_references": {
      "description": "Manifest attributes details",
      "properties": {
        "digest": {
          "type": "string",
          "description": "Manifest digest"
        },
        "architecture": {
          "type": "string",
          "description": "CPU architecture"
        },
        "os": {
          "type": "string",
          "description": "Operating system"
        }
      },
      "example": {
        "os": "os",
        "digest": "digest",
        "architecture": "architecture"
      }
    },
    "ManifestAttributes_manifest": {
      "description": "List of manifest attributes",
      "properties": {
        "references": {
          "type": "array",
          "description": "List of manifest attributes details",
          "items": {
            "$ref": "#/definitions/ManifestAttributes_manifest_references",
            "description": "Manifest attributes details"
          }
        },
        "quarantineTag": {
          "type": "string",
          "description": "Quarantine tag name"
        }
      },
      "example": {
        "quarantineTag": "quarantineTag",
        "references": [
          {
            "os": "os",
            "digest": "digest",
            "architecture": "architecture"
          },
          {
            "os": "os",
            "digest": "digest",
            "architecture": "architecture"
          }
        ]
      }
    },
    "ManifestChangeableAttributes": {
      "description": "Changeable attributes",
      "properties": {
        "deleteEnabled": {
          "type": "boolean",
          "description": "Delete enabled"
        },
        "writeEnabled": {
          "type": "boolean",
          "description": "Write enabled"
        },
        "listEnabled": {
          "type": "boolean",
          "description": "List enabled"
        },
        "readEnabled": {
          "type": "boolean",
          "description": "Read enabled"
        },
        "quarantineState": {
          "type": "string",
          "description": "Quarantine state"
        },
        "quarantineDetails": {
          "type": "string",
          "description": "Quarantine details"
        }
      },
      "example": {
        "quarantineDetails": "quarantineDetails",
        "readEnabled": true,
        "quarantineState": "quarantineState",
        "listEnabled": true,
        "deleteEnabled": true,
        "writeEnabled": true
      }
    }
  },
  "parameters": {
    "name": {
      "name": "name",
      "in": "path",
      "description": "Name of the image (including the namespace)",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "reference": {
      "name": "reference",
      "in": "path",
      "description": "A tag or a digest, pointing to a specific image",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "digest": {
      "name": "digest",
      "in": "path",
      "description": "Digest of a desired BLOB",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "metadata": {
      "name": "metadata",
      "in": "path",
      "description": "Name of the metadata",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "property": {
      "name": "property",
      "in": "path",
      "description": "Name of the property",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "queryOrderBy": {
      "name": "orderby",
      "in": "query",
      "description": "orderby query parameter",
      "required": false,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "queryNum": {
      "name": "n",
      "in": "query",
      "description": "query parameter for max number of items",
      "required": false,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "queryLast": {
      "name": "last",
      "in": "query",
      "description": "query parameter for the last item in previous query",
      "required": false,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "queryDigest": {
      "name": "digest",
      "in": "query",
      "description": "filter by digest",
      "required": false,
      "type": "string",
      "x-ms-parameter-location": "method"
    }
  }
}
