{
  "swagger": "2.0",
  "info": {
    "version": "1.1-preview",
    "title": "Anomaly Detector Client",
    "description": "The Anomaly Detector API detects anomalies automatically in time series data. It supports two kinds of mode, one is for stateless using, another is for stateful using. In stateless mode, there are three functionalities. Entire Detect is for detecting the whole series with model trained by the time series, Last Detect is detecting last point with model trained by points before. ChangePoint Detect is for detecting trend changes in time series. In stateful mode, user can store time series, the stored time series will be used for detection anomalies. Under this mode, user can still use the above three functionalities by only giving a time range without preparing time series in client side. Besides the above three functionalities, stateful model also provide group based detection and labeling service. By leveraging labeling service user can provide labels for each detection result, these labels will be used for retuning or regenerating detection models. Inconsistency detection is a kind of group based detection, this detection will find inconsistency ones in a set of time series. By using anomaly detector service, business customers can discover incidents and establish a logic flow for root cause analysis."
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "tags": [
    {
      "name": "MultivariateAnomalyDetection"
    }
  ],
  "securityDefinitions": {
    "apiKeyHeader": {
      "type": "apiKey",
      "in": "header",
      "name": "Ocp-Apim-Subscription-Key"
    }
  },
  "security": [
    {
      "apiKeyHeader": []
    }
  ],
  "x-ms-parameterized-host": {
    "hostTemplate": "{Endpoint}/anomalydetector/v1.1-preview",
    "useSchemePrefix": false,
    "parameters": [
      {
        "$ref": "#/parameters/Endpoint"
      }
    ]
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/multivariate/models": {
      "post": {
        "responses": {
          "201": {
            "description": "Submit a multivariate model training task successfully.",
            "headers": {
              "Location": {
                "description": "{endpoint}/anomalydetector/multivariate/v1.0/models/{modelId}",
                "type": "string"
              }
            }
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "Train a Multivariate Anomaly Detection Model",
        "description": "Create and train a multivariate anomaly detection model. The request must include a source parameter to indicate an externally accessible Azure storage Uri (preferably a Shared Access Signature Uri). All time-series used in generate the model must be zipped into one single file. Each time-series will be in a single CSV file in which the first column is timestamp and the second column is value.",
        "operationId": "TrainMultivariateModelAsync",
        "parameters": [
          {
            "name": "payload",
            "required": true,
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Model"
            }
          }
        ],
        "tags": [
          "MultivariateAnomalyDetection"
        ]
      },
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ModelList"
            }
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "List Multivariate Models",
        "description": "List models of a subscription",
        "operationId": "ListMultivariateModel",
        "parameters": [
          {
            "type": "int",
            "default": 0,
            "name": "$skip",
            "in": "query"
          },
          {
            "type": "int",
            "default": 10,
            "name": "$top",
            "in": "query"
          }
        ],
        "tags": [
          "MultivariateAnomalyDetection"
        ]
      }
    },
    "/multivariate/models/{modelId}": {
      "parameters": [
        {
          "name": "modelId",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Get multivariate model details successfully.",
            "schema": {
              "$ref": "#/definitions/ModelResponse"
            }
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "Get Multivariate Model",
        "description": "Get detailed information of multivariate model, including the training status and variables used in the model.",
        "operationId": "GetMultivariateModel",
        "tags": [
          "MultivariateAnomalyDetection"
        ]
      },
      "delete": {
        "responses": {
          "204": {
            "description": "Successfully marked model for deletion. Model will be removed within a predefined time period."
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "Delete Multivariate Model",
        "description": "delete model",
        "operationId": "DeleteMultivariateModel",
        "tags": [
          "MultivariateAnomalyDetection"
        ]
      }
    },
    "/multivariate/models/{modelId}/detect": {
      "parameters": [
        {
          "name": "modelId",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "post": {
        "responses": {
          "200": {
            "description": "Detect",
            "schema": {
              "$ref": "#/definitions/DetectionResultSync"
            }
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "Detect Multivariate Anomaly",
        "operationId": "DetectAnomalySync",
        "parameters": [
          {
            "name": "payload",
            "required": true,
            "in": "body",
            "schema": {
              "$ref": "#/definitions/DetectionRequestSync"
            }
          }
        ],
        "tags": [
          "MultivariateAnomalyDetection"
        ]
      }
    },
    "/multivariate/models/{modelId}/detect/jobs": {
      "parameters": [
        {
          "name": "modelId",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "post": {
        "responses": {
          "201": {
            "description": "Submit a multivariate anomaly detection task successfully.",
            "headers": {
              "Location": {
                "description": "{endpoint}/anomalydetector/v1.0-preview/results/{resultId}",
                "type": "string"
              }
            }
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "Detect Multivariate Anomaly",
        "description": "Submit detection multivariate anomaly task with the trained model of modelId, the input schema should be the same with the training request. Thus request will be complete asynchronously and will return a resultId for querying the detection result.The request should be a source link to indicate an externally accessible Azure storage Uri (preferably a Shared Access Signature Uri). All time-series used in generate the model must be zipped into one single file. Each time-series will be as follows: the first column is timestamp and the second column is value.",
        "operationId": "DetectAnomalyAsync",
        "parameters": [
          {
            "name": "payload",
            "required": true,
            "in": "body",
            "schema": {
              "$ref": "#/definitions/DetectionRequestAsync"
            }
          }
        ],
        "tags": [
          "MultivariateAnomalyDetection"
        ]
      }
    },
    "/multivariate/models/{modelId}/export": {
      "parameters": [
        {
          "name": "modelId",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Export a model package successfully.",
            "headers": {
              "content-type": {
                "description": "application/zip",
                "type": "string"
              }
            }
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "Export Multivariate Anomaly Detection Model as Zip file",
        "description": "Export multivariate anomaly detection model based on modelId",
        "operationId": "ExportModel",
        "produces": [
          "application/zip"
        ],
        "tags": [
          "MultivariateAnomalyDetection"
        ]
      }
    },
    "/multivariate/results/{resultId}": {
      "parameters": [
        {
          "name": "resultId",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Get Multivariate Anomaly Detection Result by Result Id.",
            "schema": {
              "$ref": "#/definitions/DetectionResultAsync"
            }
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "Get Multivariate Anomaly Detection Result",
        "description": "Get multivariate anomaly detection result based on resultId returned by the DetectAnomalyAsync api",
        "operationId": "GetDetectionResult",
        "tags": [
          "MultivariateAnomalyDetection"
        ]
      }
    }
  },
  "x-ms-paths": {
    "/multivariate/models?$skip=0&$top=5": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ModelList"
            }
          },
          "default": {
            "description": "Error response.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        },
        "summary": "List Multivariate Models",
        "operationId": "ListMultivariateModel",
        "parameters": [
          {
            "name": "$skip",
            "in": "query",
            "required": false,
            "type": "integer",
            "default": 0,
            "description": "$skip indicates how many models will be skipped."
          },
          {
            "name": "$top",
            "in": "query",
            "required": false,
            "type": "integer",
            "default": 5,
            "description": "$top indicates how many models will be fetched."
          }
        ],
        "tags": [
          "MultivariateAnomalyDetection"
        ],
        "x-ms-examples": {
          "List Multivariate model": {
            "$ref": "./examples/ListModel.json"
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink",
          "itemName": "models"
        },
        "description": "List models of a subscription"
      }
    }
  },
   "definitions": {
    "Model": {
      "required": [
        "endTime",
        "source",
        "startTime",
        "status"
      ],
      "properties": {
        "slidingWindow": {
          "type": "integer",
          "description": "An optional field, indicates how many history points will be used to determine the anomaly score of one subsequent point.",
          "example": 28
        },
        "alignPolicy": {
          "description": "An optional field, since those multivariate need to be aligned in the same timestamp before starting the detection.",
          "allOf": [
            {
              "$ref": "#/definitions/AlignPolicy"
            }
          ]
        },
        "source": {
          "type": "string",
          "description": "required field, source file link of the input variables, each variable will be a csv with two columns, the firstcolumn will be timestamp, the second column will be value.Besides these variable csv files, a extra meta.json can beincluded in th zip file if you would like to rename a variable.Be default, the file name of the variable will be used as thevariable name.",
          "example": "https://multiadsample.blob.core.windows.net/data/sample_data_2_1000.zip?sp=rl&st=2020-12-04T06:03:47Z&se=2022-12-05T06:03:00Z&sv=2019-12-12&sr=b&sig=AZTbvZ7fcp3MdqGY%2FvGHJXJjUgjS4DneCGl7U5omq5c%3D"
        },
        "startTime": {
          "type": "string",
          "description": "require field, start time of data be used for generating multivariate anomaly detection model, should be data-time",
          "example": "2010-01-01T00:00:00Z"
        },
        "endTime": {
          "type": "string",
          "description": "require field, end time of data be used for generating multivariate anomaly detection model, should be data-time",
          "example": "2010-01-03T00:00:00Z"
        },
        "displayName": {
          "type": "string",
          "example": "DevOps-Test"
        },
        "status": {
          "type": "string",
          "description": "Model training status.",
          "example": "READY",
          "enum": [
            "CREATED",
            "RUNNING",
            "READY",
            "FAILED"
          ]
        },
        "errors": {
          "type": "array",
          "description": "Error message when fails to create a model.",
          "items": {
            "$ref": "#/definitions/ErrorResponse"
          }
        },
        "diagnosticsInfo": {
          "$ref": "#/definitions/DiagnoseInfo"
        }
      },
      "type": "object"
    },
    "AlignPolicy": {
      "properties": {
        "alignMode": {
          "type": "string",
          "description": "An optional field, indicates how we align different variables into the same time-range which is required by the model.{Inner, Outer}",
          "example": "Outer",
          "enum": [
            "Inner",
            "Outer"
          ]
        },
        "fillNAMethod": {
          "type": "string",
          "description": "An optional field, indicates how missed values will be filled with. Can not be set to NotFill, when alignMode is Outer.{Previous, Subsequent, Linear, Zero, Fixed, NotFill}",
          "example": "Linear",
          "enum": [
            "Previous",
            "Subsequent",
            "Linear",
            "Zero",
            "Fixed",
            "NotFill"
          ]
        },
        "paddingValue": {
          "type": "integer",
          "description": "optional field, only be useful if FillNAMethod is set to Pad."
        }
      },
      "type": "object"
    },
    "ErrorResponse": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string",
          "description": "The error Code"
        },
        "message": {
          "type": "string",
          "description": "A message explaining the error reported by the service."
        }
      },
      "type": "object"
    },
    "DiagnoseInfo": {
      "properties": {
        "modelState": {
          "$ref": "#/definitions/ModelState"
        },
        "variableStates": {
          "type": "array",
          "example": [
            {
              "variable": "ad_input",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            },
            {
              "variable": "ad_ontimer_output",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            },
            {
              "variable": "ingestion",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            },
            {
              "variable": "data_in_speed",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            },
            {
              "variable": "cpu",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            },
            {
              "variable": "ad_series_init",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            },
            {
              "variable": "flink_last_ckpt_duration",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            },
            {
              "variable": "data_out_speed",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            },
            {
              "variable": "ad_output",
              "filledNARatio": 0,
              "effectiveCount": 1441,
              "startTime": "2019-04-01T00:00:00Z",
              "endTime": "2019-04-02T00:00:00Z",
              "errors": []
            }
          ],
          "items": {
            "$ref": "#/definitions/VariableState"
          }
        }
      },
      "type": "object"
    },
    "ModelState": {
      "properties": {
        "epochIds": {
          "type": "array",
          "description": "Epoch id",
          "example": [
            10,
            20,
            30,
            40,
            50,
            60,
            70,
            80,
            90,
            100
          ],
          "items": {
            "type": "integer"
          }
        },
        "trainLosses": {
          "type": "array",
          "example": [
            0.6291328072547913,
            0.1671326905488968,
            0.12354248017072678,
            0.10259664058685303,
            0.09584927558898926,
            0.09069952368736267,
            0.08686016499996185,
            0.08603022992610931,
            0.08287354558706284,
            0.08235538005828857
          ],
          "items": {
            "type": "number"
          }
        },
        "validationLosses": {
          "type": "array",
          "example": [
            0.9573427438735962,
            0.3182229995727539,
            0.3402646481990814,
            0.27653488516807556,
            0.2574014365673065,
            0.26928603649139404,
            0.2637230455875397,
            0.2590833008289337,
            0.2597166895866394,
            0.25973501801490784
          ],
          "items": {
            "type": "number"
          }
        },
        "latenciesInSeconds": {
          "type": "array",
          "example": [
            0.3398594856262207,
            0.3659665584564209,
            0.37360644340515137,
            0.35134077072143555,
            0.33703041076660156,
            0.31876277923583984,
            0.32833099365234375,
            0.3503587245941162,
            0.3080024719238281,
            0.3327946662902832
          ],
          "items": {
            "type": "number"
          }
        }
      },
      "type": "object"
    },
    "VariableState": {
      "properties": {
        "variable": {
          "type": "string",
          "description": "Variable name."
        },
        "filledNARatio": {
          "type": "number",
          "description": "Missing ratio of a variable."
        },
        "effectiveCount": {
          "type": "integer",
          "description": "Effective time-series points count."
        },
        "startTime": {
          "type": "string",
          "description": "Start time of a variable"
        },
        "endTime": {
          "type": "string",
          "description": "End time of a variable"
        },
        "errors": {
          "type": "array",
          "description": "Error message when parse variable",
          "items": {
            "$ref": "#/definitions/ErrorResponse"
          }
        }
      },
      "type": "object"
    },
    "ModelList": {
      "required": [
        "currentCount",
        "maxCount",
        "models"
      ],
      "properties": {
        "models": {
          "type": "array",
          "description": "List of models",
          "items": {
            "$ref": "#/definitions/ModelSnapshot"
          }
        },
        "currentCount": {
          "type": "integer",
          "description": "Current count of trained multivariate models.",
          "example": 1
        },
        "maxCount": {
          "type": "integer",
          "description": "Max number of models that can be trained for this subscription.",
          "example": 50
        },
        "nextLink": {
          "type": "string",
          "description": "next link to fetch more models"
        }
      },
      "type": "object"
    },
    "ModelSnapshot": {
      "required": [
        "createdTime",
        "lastUpdatedTime",
        "modelId",
        "status",
        "variablesCount"
      ],
      "properties": {
        "modelId": {
          "type": "string",
          "description": "Model identifier.",
          "example": "45aad126-aafd-11ea-b8fb-d89ef3400c5f"
        },
        "createdTime": {
          "type": "string",
          "description": "Date and time (UTC) when the model was created.",
          "example": "2020-06-30T00:00:00Z"
        },
        "lastUpdatedTime": {
          "type": "string",
          "description": "Date and time (UTC) when the model was last updated.",
          "example": "2020-06-30T00:00:00Z"
        },
        "status": {
          "type": "string",
          "description": "Model training status.",
          "example": "READY",
          "enum": [
            "CREATED",
            "RUNNING",
            "READY",
            "FAILED"
          ]
        },
        "displayName": {
          "type": "string",
          "example": "DevOps-Test"
        },
        "variablesCount": {
          "type": "integer",
          "description": "Count of variables",
          "example": 18
        }
      },
      "type": "object"
    },
    "ModelResponse": {
      "required": [
        "createdTime",
        "lastUpdatedTime",
        "modelId",
        "modelInfo"
      ],
      "properties": {
        "modelId": {
          "type": "string",
          "description": "Model identifier.",
          "example": "45aad126-aafd-11ea-b8fb-d89ef3400c5f"
        },
        "createdTime": {
          "type": "string",
          "description": "Date and time (UTC) when the model was created.",
          "example": "2020-06-30T00:00:00Z"
        },
        "lastUpdatedTime": {
          "type": "string",
          "description": "Date and time (UTC) when the model was last updated.",
          "example": "2020-06-30T00:00:00Z"
        },
        "modelInfo": {
          "description": "Training Status of the model.",
          "allOf": [
            {
              "$ref": "#/definitions/Model"
            }
          ]
        }
      },
      "type": "object"
    },
    "DetectionRequestAsync": {
      "required": [
        "endTime",
        "source",
        "startTime"
      ],
      "properties": {
        "source": {
          "type": "string",
          "description": "required field, source file link of the input variables, each variable will be a csv with two columns, the first column will be timestamp, the second column will be value.Besides these variable csv files, a extra meta.json can be included in th zip file if you would like to rename a variable.Be default, the file name of the variable will be used as the variable name. The variables used in detection should be consistent with variables in the model used for detection.",
          "example": "https://multiadsample.blob.core.windows.net/data/sample_data_2_1000.zip?sp=rl&st=2020-12-04T06:03:47Z&se=2022-12-05T06:03:00Z&sv=2019-12-12&sr=b&sig=AZTbvZ7fcp3MdqGY%2FvGHJXJjUgjS4DneCGl7U5omq5c%3D"
        },
        "startTime": {
          "type": "string",
          "description": "A require field, start time of data be used for detection, should be date-time.",
          "example": "2010-01-01T00:00:00Z"
        },
        "endTime": {
          "type": "string",
          "description": "A require field, end time of data be used for detection, should be date-time.",
          "example": "2010-01-03T00:00:00Z"
        }
      },
      "type": "object"
    },
    "DetectionRequestSync": {
      "required": [
        "length",
        "variables"
      ],
      "properties": {
        "variables": {
          "type": "array",
          "description": "variables",
          "example": [
            {
              "variableName": "Variable_1",
              "timestamps": [
                "2021-01-01T00:00:00Z",
                "2021-01-01T00:01:00Z",
                "2021-01-01T00:02:00Z",
                "2021-01-01T00:03:00Z",
                "2021-01-01T00:04:00Z",
                "2021-01-01T00:05:00Z",
                "2021-01-01T00:06:00Z",
                "2021-01-01T00:07:00Z",
                "2021-01-01T00:08:00Z",
                "2021-01-01T00:09:00Z",
                "2021-01-01T00:10:00Z",
                "2021-01-01T00:11:00Z",
                "2021-01-01T00:12:00Z",
                "2021-01-01T00:13:00Z",
                "2021-01-01T00:14:00Z",
                "2021-01-01T00:15:00Z",
                "2021-01-01T00:16:00Z",
                "2021-01-01T00:17:00Z",
                "2021-01-01T00:18:00Z",
                "2021-01-01T00:19:00Z",
                "2021-01-01T00:20:00Z",
                "2021-01-01T00:21:00Z",
                "2021-01-01T00:22:00Z",
                "2021-01-01T00:23:00Z",
                "2021-01-01T00:24:00Z",
                "2021-01-01T00:25:00Z",
                "2021-01-01T00:26:00Z",
                "2021-01-01T00:27:00Z",
                "2021-01-01T00:28:00Z",
                "2021-01-01T00:29:00Z"
              ],
              "values": [
                0.4551378545933972,
                0.7388603950488748,
                0.201088255984052,
                0.7462812245891899,
                0.07308128850401663,
                0.33090474587393537,
                0.7544925268153315,
                0.987506336316328,
                0.6665932993421468,
                0.6308351543168672,
                0.08083310161466228,
                0.8414415588668442,
                0.514583545640453,
                0.0954489875193526,
                0.7786793231920507,
                0.41646133667960994,
                0.030176187583339287,
                0.3474214937189324,
                0.508530173413991,
                0.42451199127255046,
                0.2115944222725208,
                0.24733519545833516,
                0.8791022110982156,
                0.9479621899884665,
                0.26702703121252136,
                0.6954503497669413,
                0.1235728391488995,
                0.8214915473050647,
                0.11813002444192677,
                0.8579045951076123
              ]
            },
            {
              "variableName": "Variable_2",
              "timestamps": [
                "2021-01-01T00:00:00Z",
                "2021-01-01T00:01:00Z",
                "2021-01-01T00:02:00Z",
                "2021-01-01T00:03:00Z",
                "2021-01-01T00:04:00Z",
                "2021-01-01T00:05:00Z",
                "2021-01-01T00:06:00Z",
                "2021-01-01T00:07:00Z",
                "2021-01-01T00:08:00Z",
                "2021-01-01T00:09:00Z",
                "2021-01-01T00:10:00Z",
                "2021-01-01T00:11:00Z",
                "2021-01-01T00:12:00Z",
                "2021-01-01T00:13:00Z",
                "2021-01-01T00:14:00Z",
                "2021-01-01T00:15:00Z",
                "2021-01-01T00:16:00Z",
                "2021-01-01T00:17:00Z",
                "2021-01-01T00:18:00Z",
                "2021-01-01T00:19:00Z",
                "2021-01-01T00:20:00Z",
                "2021-01-01T00:21:00Z",
                "2021-01-01T00:22:00Z",
                "2021-01-01T00:23:00Z",
                "2021-01-01T00:24:00Z",
                "2021-01-01T00:25:00Z",
                "2021-01-01T00:26:00Z",
                "2021-01-01T00:27:00Z",
                "2021-01-01T00:28:00Z",
                "2021-01-01T00:29:00Z"
              ],
              "values": [
                0.9617871613964145,
                0.24903311574778408,
                0.4920561254118613,
                0.9895601049618598,
                0.9171759283128094,
                0.5754204711105273,
                0.1811033296265634,
                0.8852311981742577,
                0.9543231904644779,
                0.7088012446094262,
                0.7843572237149014,
                0.7664787010700046,
                0.3699552325387093,
                0.504519908266789,
                0.5848930929950164,
                0.7628913396089576,
                0.8148405868900065,
                0.08540458873739332,
                0.03481976727525682,
                0.21275099339467762,
                0.9836175579199806,
                0.9321441483364282,
                0.038466608085469534,
                0.1723138437622782,
                0.8626383410218382,
                0.35053229974224254,
                0.631141662835182,
                0.0730352607990088,
                0.08886179043386,
                0.7488606040971179
              ]
            },
            {
              "variableName": "Variable_3",
              "timestamps": [
                "2021-01-01T00:00:00Z",
                "2021-01-01T00:01:00Z",
                "2021-01-01T00:02:00Z",
                "2021-01-01T00:03:00Z",
                "2021-01-01T00:04:00Z",
                "2021-01-01T00:05:00Z",
                "2021-01-01T00:06:00Z",
                "2021-01-01T00:07:00Z",
                "2021-01-01T00:08:00Z",
                "2021-01-01T00:09:00Z",
                "2021-01-01T00:10:00Z",
                "2021-01-01T00:11:00Z",
                "2021-01-01T00:12:00Z",
                "2021-01-01T00:13:00Z",
                "2021-01-01T00:14:00Z",
                "2021-01-01T00:15:00Z",
                "2021-01-01T00:16:00Z",
                "2021-01-01T00:17:00Z",
                "2021-01-01T00:18:00Z",
                "2021-01-01T00:19:00Z",
                "2021-01-01T00:20:00Z",
                "2021-01-01T00:21:00Z",
                "2021-01-01T00:22:00Z",
                "2021-01-01T00:23:00Z",
                "2021-01-01T00:24:00Z",
                "2021-01-01T00:25:00Z",
                "2021-01-01T00:26:00Z",
                "2021-01-01T00:27:00Z",
                "2021-01-01T00:28:00Z",
                "2021-01-01T00:29:00Z"
              ],
              "values": [
                0.4030756879437628,
                0.15526889968448554,
                0.36352226408981103,
                0.6051200637229004,
                0.8516795018476276,
                0.2645605735279929,
                0.6810875830037345,
                0.9165894221681316,
                0.700783245230424,
                0.5624155469940331,
                0.6277289685127893,
                0.15992056539730204,
                0.6020964482827594,
                0.35937967753105915,
                0.8731686034848609,
                0.20301549117588935,
                0.029261872151168933,
                0.6261499548828445,
                0.45850782028563386,
                0.8275006940083313,
                0.032760268834037376,
                0.4485202784055029,
                0.8915691008748384,
                0.891669051517807,
                0.9469979353323046,
                0.115293087370132,
                0.08818772518459506,
                0.7426286620589166,
                0.32372247468990756,
                0.936268139507417
              ]
            }
          ],
          "items": {
            "$ref": "#/definitions/VariableContent"
          }
        },
        "length": {
          "type": "integer",
          "description": "length",
          "example": 2
        }
      },
      "type": "object"
    },
    "VariableContent": {
      "required": [
        "name",
        "timestamps",
        "values"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "variable name",
          "example": "variable_1"
        },
        "timestamps": {
          "type": "array",
          "description": "timestamps",
          "items": {
            "type": "string"
          }
        },
        "values": {
          "type": "array",
          "description": "values",
          "items": {
            "type": "number"
          }
        }
      },
      "type": "object"
    },
    "DetectionResultSync": {
      "required": [
        "results",
        "variableStates"
      ],
      "properties": {
        "variableStates": {
          "type": "array",
          "example": [
            {
              "variable": "variable_1",
              "filledNARatio": 0,
              "effectiveCount": 30,
              "startTime": "2021-01-01T00:00:00Z",
              "endTime": "2021-01-01T00:29:00Z",
              "errors": []
            },
            {
              "variable": "variable_2",
              "filledNARatio": 0,
              "effectiveCount": 30,
              "startTime": "2021-01-01T00:00:00Z",
              "endTime": "2021-01-01T00:29:00Z",
              "errors": []
            },
            {
              "variable": "variable_3",
              "filledNARatio": 0,
              "effectiveCount": 30,
              "startTime": "2021-01-01T00:00:00Z",
              "endTime": "2021-01-01T00:29:00Z",
              "errors": []
            }
          ],
          "items": {
            "$ref": "#/definitions/VariableState"
          }
        },
        "results": {
          "type": "array",
          "example": [
            {
              "timestamp": "2021-01-01T00:28:00Z",
              "value": {
                "isAnomaly": false,
                "severity": 0,
                "score": 0.6928471326828003
              },
              "errors": []
            },
            {
              "timestamp": "2021-01-01T00:29:00Z",
              "value": {
                "isAnomaly": true,
                "severity": 0.5337404608726501,
                "score": 0.9171165823936462,
                "interpretation": {
                  "variables": [
                    "variable_2",
                    "variable_3",
                    "variable_1"
                  ],
                  "contributorScores": [
                    53.71576215,
                    33.24159383,
                    13.04264402
                  ],
                  "correlcationChanges": [
                    {
                      "variables": [
                        "variable_1",
                        "variable_3"
                      ],
                      "changes": [
                        0.1741322,
                        -0.1093203
                      ]
                    },
                    {
                      "variables": [
                        "variable_2"
                      ],
                      "changes": [
                        0.1229392
                      ]
                    },
                    {
                      "variables": [],
                      "changes": []
                    }
                  ]
                }
              },
              "errors": []
            }
          ],
          "items": {
            "$ref": "#/definitions/AnomalyState"
          }
        },
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ErrorResponse"
          }
        }
      },
      "type": "object"
    },
    "AnomalyState": {
      "required": [
        "timestamp"
      ],
      "properties": {
        "timestamp": {
          "type": "string",
          "description": "timestamp",
          "example": "2020-01-01T00:00:00Z"
        },
        "value": {
          "$ref": "#/definitions/AnomalyValue"
        },
        "errors": {
          "type": "array",
          "description": "Error message when inference this timestamp",
          "items": {
            "$ref": "#/definitions/ErrorResponse"
          }
        }
      },
      "type": "object"
    },
    "AnomalyValue": {
      "required": [
        "isAnomaly",
        "score",
        "severity"
      ],
      "properties": {
        "score": {
          "type": "number",
          "description": "score",
          "example": 0.8
        },
        "severity": {
          "type": "number",
          "description": "severity",
          "example": 0.5
        },
        "isAnomaly": {
          "type": "boolean",
          "description": "whether there is an anomaly at the current timestamp",
          "example": true
        },
        "interpretation": {
          "description": "interpretation of the anomaly",
          "allOf": [
            {
              "$ref": "#/definitions/Interpretation"
            }
          ]
        }
      },
      "type": "object"
    },
    "Interpretation": {
      "required": [
        "contributorScores",
        "contributors",
        "correlationChanges"
      ],
      "properties": {
        "contributors": {
          "type": "array",
          "description": "contributors",
          "items": {
            "type": "string"
          }
        },
        "contributorScores": {
          "type": "array",
          "description": "contributor scores",
          "items": {
            "type": "number"
          }
        },
        "correlcationChanges": {
          "type": "array",
          "description": "correlation changes",
          "items": {
            "$ref": "#/definitions/CorrelationChanges"
          }
        }
      },
      "type": "object"
    },
    "CorrelationChanges": {
      "properties": {
        "variables": {
          "type": "array",
          "description": "correlated variables",
          "items": {
            "type": "string"
          }
        },
        "changes": {
          "type": "array",
          "description": "changes in correlation",
          "items": {
            "type": "number"
          }
        }
      },
      "type": "object"
    },
    "DetectionResultAsync": {
      "required": [
        "resultId",
        "results",
        "summary"
      ],
      "properties": {
        "resultId": {
          "type": "string",
          "example": "45aad126-aafd-11ea-b8fb-d89ef3400c5f"
        },
        "summary": {
          "description": "Multivariate anomaly detection status",
          "example": {
            "status": "READY",
            "errors": [],
            "variableStates": [
              {
                "variable": "variable_1",
                "filledNARatio": 0,
                "effectiveCount": 30,
                "startTime": "2021-01-01T00:00:00Z",
                "endTime": "2021-01-01T00:29:00Z",
                "errors": []
              },
              {
                "variable": "variable_2",
                "filledNARatio": 0,
                "effectiveCount": 30,
                "startTime": "2021-01-01T00:00:00Z",
                "endTime": "2021-01-01T00:29:00Z",
                "errors": []
              },
              {
                "variable": "variable_3",
                "filledNARatio": 0,
                "effectiveCount": 30,
                "startTime": "2021-01-01T00:00:00Z",
                "endTime": "2021-01-01T00:29:00Z",
                "errors": []
              }
            ],
            "setupInfo": {
              "source": "https://sampledatamvad.blob.core.windows.net/sample/inference_iot_sudden_drop.zip?sp=r&st=2021-08-05T03:51:07Z&se=2023-06-07T11:51:07Z&spr=https&sv=2020-08-04&sr=b&sig=hxvAixxN3ZnjdIIaK4%2BdULEAu0xZ3Cmov3QLABbKneQ%3D",
              "startTime": "2021-01-01T00:28:00Z",
              "endTime": "2021-01-01T00:29:00Z"
            }
          },
          "allOf": [
            {
              "$ref": "#/definitions/DetectionResultSummary"
            }
          ]
        },
        "results": {
          "type": "array",
          "description": "result",
          "example": [
            {
              "timestamp": "2021-01-01T00:28:00Z",
              "value": {
                "isAnomaly": false,
                "severity": 0,
                "score": 0.6928471326828003
              },
              "errors": []
            },
            {
              "timestamp": "2021-01-01T00:29:00Z",
              "value": {
                "isAnomaly": true,
                "severity": 0.5337404608726501,
                "score": 0.9171165823936462,
                "interpretation": {
                  "variables": [
                    "variable_2",
                    "variable_3",
                    "variable_1"
                  ],
                  "contributorScores": [
                    53.71576215,
                    33.24159383,
                    13.04264402
                  ],
                  "correlcationChanges": [
                    {
                      "variables": [
                        "variable_1",
                        "variable_3"
                      ],
                      "changes": [
                        0.1741322,
                        -0.1093203
                      ]
                    },
                    {
                      "variables": [
                        "variable_2"
                      ],
                      "changes": [
                        0.1229392
                      ]
                    },
                    {
                      "variables": [],
                      "changes": []
                    }
                  ]
                }
              },
              "errors": []
            }
          ],
          "items": {
            "$ref": "#/definitions/AnomalyState"
          }
        }
      },
      "type": "object"
    },
    "DetectionResultSummary": {
      "required": [
        "setupInfo",
        "status"
      ],
      "properties": {
        "status": {
          "type": "string",
          "description": "Multivariate anomaly detection status",
          "example": "READY",
          "enum": [
            "CREATED",
            "RUNNING",
            "READY",
            "FAILED"
          ]
        },
        "errors": {
          "type": "array",
          "description": "Error message when creating or training model fails.",
          "items": {
            "$ref": "#/definitions/ErrorResponse"
          }
        },
        "variableStates": {
          "type": "array",
          "example": [
            {
              "variable": "variable_1",
              "filledNARatio": 0,
              "effectiveCount": 30,
              "startTime": "2021-01-01T00:00:00Z",
              "endTime": "2021-01-01T00:29:00Z",
              "errors": []
            },
            {
              "variable": "variable_2",
              "filledNARatio": 0,
              "effectiveCount": 30,
              "startTime": "2021-01-01T00:00:00Z",
              "endTime": "2021-01-01T00:29:00Z",
              "errors": []
            },
            {
              "variable": "variable_3",
              "filledNARatio": 0,
              "effectiveCount": 30,
              "startTime": "2021-01-01T00:00:00Z",
              "endTime": "2021-01-01T00:29:00Z",
              "errors": []
            }
          ],
          "items": {
            "$ref": "#/definitions/VariableState"
          }
        },
        "setupInfo": {
          "description": "Request when creating the model.",
          "allOf": [
            {
              "$ref": "#/definitions/DetectionRequestAsync"
            }
          ]
        }
      },
      "type": "object"
    }
  },
  "parameters": {
    "Endpoint": {
      "name": "Endpoint",
      "description": "Supported Cognitive Services endpoints (protocol and hostname, for example: https://westus2.api.cognitive.microsoft.com).",
      "x-ms-parameter-location": "client",
      "required": true,
      "type": "string",
      "in": "path",
      "x-ms-skip-url-encoding": true
    }
  }
}
